
name: Contribution Check - Git Inspector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inspect:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
