name: Dynamic code Analysis - Valgrind
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install valgrind
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 4_Implementaion/ test
    - name: Valgrind
      run: valgrind ./4_Implementaion/Build/Test_halfwave-fullwave.out